version: '1'
services:
  db:
    container_name: testbakapp
    image: postgres:13
    volumes:
      - testbakapp:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test_bank_app
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

volumes:
  sample_db: { }